### ISSUE TITLE
Update catalyst-demo-ui to support discovery protocol

### ISSUE THREAD

**Issue by andrewwhitehead** [bcgov/aries-vcr#282]
Support querying for all supported protocols or use a query string, and display the results in the UI.

**Comment by swcurran** [comment]
@andrewwhitehead - another one for you to look at. Close? Move to ACA-Py?

**Comment by andrewwhitehead** [comment]
@swcurran Another one related to the AgentBook UI. I don't think there's an immediate use case for this one, although it would be nice to have.
