### ISSUE TITLE
Credentials View Details Behavior is Inconsistent for Relationships and Credentials

### ISSUE THREAD

**Issue by seanadipose** [bcgov/aries-vcr#388]
## Details Link Behavior Inconsistent on the Topic Form Page in Tob-Web

The details link view page shows as an <a> tag and clickable when the item displayed is a credential however the link is not clickable.

When the item displayed is a relationship the url works correctly and is clickable by the user as expected.

https://orgbook.gov.bc.ca/en/organization/BC1101218

![image](https://user-images.githubusercontent.com/37384199/64883450-3cd82900-d614-11e9-9c7a-875afd7a44f4.png)

**Comment by jljordan42** [comment]
That seems to be the situation where that link isn’t there because it’s actually the page that is being displays ... so that text should not be a link but just text.
