### ISSUE TITLE
Issuer Registration message is missing attributes

### ISSUE THREAD

**Issue by ianco** [bcgov/aries-vcr#441]
Message received by OrgBook is missing attributes:

- credential type "endpoint_en" and "label_en"
- address fields mappings (only "address_type" is received by orgbook)
- issuer fields "abbreviation_en", "label_en", "logo_b64", "url_en"

**Comment by ianco** [comment]
Address and logo fixed.

Language-specific fields will be added in a separate ticket

**Comment by esune** [comment]
@ianco moving this to done, since I believe the relevant PRs have been merged.
