### ISSUE TITLE
Review the recent alerts against Aries VCR - particularly the one marked severe

### ISSUE THREAD

**Issue by swcurran** [bcgov/aries-vcr#479]
Please review and address (apply or dismiss) the alerts found on the alerts page - https://github.com/bcgov/aries-vcr/network/alerts

**Comment by esune** [comment]
@swcurran I don't see security alerts for aries-vcr: if you can still see them, can you please check whether I am authorized to see the tab in GitHub (I may need to be an admin?).

**Comment by WadeBarnes** [comment]
@esune, have a look now.

**Comment by esune** [comment]
@wadebarnes I still get a 404

**Comment by WadeBarnes** [comment]
@esune, try now.

**Comment by esune** [comment]
@WadeBarnes it works now, thank you.
