### ISSUE TITLE
Investigate duplicate data

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/aries-vcr#487]
Found in:
- 87c6bd423f537231d36ffa8ae8c26f91247f3b9f

The following record appears to have a lot of duplicate data, please investigate.
https://orgbook-dev.pathfinder.gov.bc.ca/en/organization/demo.verified_person.registries.ca/VPCLUTCHLULANI

**Comment by ianco** [comment]
Individual shows duplicated director relationships to:

                    'BC0036103',
                    'BC0014947',
                    'BC0020288',
                    'BC0163588',
                    'BC0187871',

**Comment by ianco** [comment]
Relationships are showing multiple times because the individual has multiple relationships with the organization.

For example a separate relationship is displayed when the user is both a DIRECTOR and OFFICER of the corporation.

The information displayed matches the information in the BC Reg database (corp_party table)

**Comment by WadeBarnes** [comment]
Now that you've mentioned that, in conjunction with the info provided in this ticket, https://github.com/bcgov/aries-vcr/issues/489, I can see that.  Without that context it's very confusing.

So it's fairly clear in this section of the page:
![image](https://user-images.githubusercontent.com/10504350/80833891-6d210780-8ba4-11ea-902e-e57b0a9bfe88.png)

But it's not clear at all in this section of the page:
![image](https://user-images.githubusercontent.com/10504350/80833979-9c377900-8ba4-11ea-9813-3288e31c1f5a.png)

**Comment by WadeBarnes** [comment]
@jljordan42, @swcurran -- FYI - a UX issue that is going onto the backlog.
