### ISSUE TITLE
Typo - Associated Registration Name

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/aries-vcr#488]
Associated Registration Name is misspelled.

Found in:
- 87c6bd423f537231d36ffa8ae8c26f91247f3b9f

Example:
- https://orgbook-dev.pathfinder.gov.bc.ca/en/organization/registration.registries.ca/BC0640905/cred/4131860

![image](https://user-images.githubusercontent.com/10504350/80507203-70f62500-892b-11ea-9faf-b7597e3d30af.png)

**Comment by ianco** [comment]
Relationship from director to BC0640905

**Comment by WadeBarnes** [comment]
@ianco, I don't see a fix for this.

**Comment by ianco** [comment]
It's in this PR:  https://github.com/bcgov/von-bc-registries-agent/pull/232

**Comment by WadeBarnes** [comment]
But the typo still exists;
![image](https://user-images.githubusercontent.com/10504350/81076449-7eb62800-8ea0-11ea-88ae-a772c944e7a7.png)

**Comment by WadeBarnes** [comment]
Never mind.  Issuer registration issue.  It wasn't clear from this ticket the fix was on that side.

**Comment by WadeBarnes** [comment]
Resolved in https://github.com/bcgov/von-bc-registries-agent/commit/488934afa6f080d12e4ed6f8014fe4f8b48c277a

Verified the spelling mistake has been fixed:
![image](https://user-images.githubusercontent.com/10504350/81079368-53cdd300-8ea4-11ea-98c7-2ef5b5822706.png)
