### ISSUE TITLE
Inconsistent credential timeline views

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/aries-vcr#491]
Found in:
- 87c6bd423f537231d36ffa8ae8c26f91247f3b9f

Example data:
- https://orgbook-test.pathfinder.gov.bc.ca/en/organization/registration.registries.ca/BC0337062

Observed:
- The credential timelines are **not** rendered in a consistent manner.

Expected:
- The credential timelines are rendered in a consistent manner.

On the Organization page the credential timeline is displayed like this:
![image](https://user-images.githubusercontent.com/10504350/80603114-d3f7c280-89e4-11ea-8f15-911fe8f3336e.png)

If you view any of the registration credentials for the corp you see the credential timeline is displayed like this:
![image](https://user-images.githubusercontent.com/10504350/80603429-44064880-89e5-11ea-85f4-587b469383d5.png)

**Comment by ianco** [comment]
BC0337062

**Comment by ianco** [comment]
These pages are populated by two different back-end services.

For the company page:
http://localhost:8080/api/topic/64/credentialset
... which has no details for the topic's credentials

For the credential page:
http://localhost:8080/api/credential/145/formatted
... which has a local_name attribute and attribute details ...

I'll check the topic credentialset api and see what's involved to add the necessary attributes.

**Comment by ianco** [comment]
Added name info to credentials returned from the topic credentialset api.

Note - this info was removed during the performance improvements done recently, so adding this data back (required by the UI) may have a performance impact.

**Comment by WadeBarnes** [comment]
Resolved in 25c1c3a0b961ab4a0b82bd18b0ce0778a1d9bb18

Verified the credential timelines are rendered consistently.

Organization page:
![image](https://user-images.githubusercontent.com/10504350/81075507-50841880-8e9f-11ea-9577-5018e3293886.png)

Registration page:
![image](https://user-images.githubusercontent.com/10504350/81075591-68f43300-8e9f-11ea-8c5e-35568f3882ac.png)
