### ISSUE TITLE
Results of some proof requests are not being rendered

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/aries-vcr#492]
Found in:
- 87c6bd423f537231d36ffa8ae8c26f91247f3b9f

Examples:
- https://orgbook-test.pathfinder.gov.bc.ca/en/organization/registration.registries.ca/BC0337062/cred/447175/verify
  - Results of proof request rendered.
- https://orgbook-test.pathfinder.gov.bc.ca/en/organization/registration.registries.ca/BC0337062/cred/447225/verify
  - Results of proof request **not** rendered.
- https://orgbook-test.pathfinder.gov.bc.ca/en/organization/registration.registries.ca/BC0337062/cred/447299/verify
  - Results of proof request **not** rendered.

Observed:
- The results of some proof requests are **not** being rendered.

Expected:
- The results of all proof requests are rendered.

Rendered:
![image](https://user-images.githubusercontent.com/10504350/80604450-985df800-89e6-11ea-97b5-b8008a13016c.png)

Not rendered:
![image](https://user-images.githubusercontent.com/10504350/80604514-ab70c800-89e6-11ea-86a6-46d10c1b14be.png)

**Comment by ianco** [comment]
BC0337062

Initial test seemed to work, but was very slow

**Comment by ianco** [comment]
Credentials that are expired are no longer verifiable.

This message is displayed on the credential screen (e.g. https://orgbook-test.pathfinder.gov.bc.ca/en/organization/registration.registries.ca/BC0337062/cred/447225) but not on the verify screen.

The screen is for "Claims proven and verified" so this screen should probably *not* be linked for credentials that can't be verified.

@swcurran ?

**Comment by ianco** [comment]
Hide the "View data for this credential" for expired credentials (don't link to the verify page).

**Comment by WadeBarnes** [comment]
Resolved in 25c1c3a0b961ab4a0b82bd18b0ce0778a1d9bb18

Verified the "See data for this credential" link is not available for expired creds;

Active:
![image](https://user-images.githubusercontent.com/10504350/81075065-bae88900-8e9e-11ea-9b0e-a84e670a7cd7.png)

Expired:
![image](https://user-images.githubusercontent.com/10504350/81075106-c9cf3b80-8e9e-11ea-8fdb-c2afafd3c5d3.png)
