### ISSUE TITLE
Advanced Search not working as expected

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/aries-vcr#494]
Found in:
- 87c6bd423f537231d36ffa8ae8c26f91247f3b9f

Steps to reproduce:
- https://orgbook-test.pathfinder.gov.bc.ca/en/advanced-search
![image](https://user-images.githubusercontent.com/10504350/80608690-fd681c80-89eb-11ea-9206-9a1c3a7bd232.png)

Observed:
- The resulting company records are not displaying any relationship credentials.

Expected:
- The resulting records to displaying relationship credentials.

**Comment by ianco** [comment]
Probably another candidate for a UI review @swcurran @jljordan42 

This is actually a Topic Search, and the filter is "topics that have a credential of the selected type".

So when you select "relationship" then you see topics (i.e. companies) that have a relationship credential.
