### ISSUE TITLE
Delay updating the search page results when paging

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/aries-vcr#495]
Found in:
- 87c6bd423f537231d36ffa8ae8c26f91247f3b9f

Steps to reproduce:
- Perform a partial name search to return many results:
![image](https://user-images.githubusercontent.com/10504350/80609738-52f0f900-89ed-11ea-9dfa-3c57d540f69b.png)
- Make note of the search results.
- Click **Next** to go to the next page.
- Make note of the page number in the URL and the list of results.

Observed:
- The page scrolls to the top of the list and the URL indicates it is on the next page.
- The results of the previous page are still listed for a few moments before the results of the current page are finally displayed.

**Page 1 results:**
![image](https://user-images.githubusercontent.com/10504350/80609987-a19e9300-89ed-11ea-897b-8de2b1e48b40.png)

**Page 2 results (start):**
![image](https://user-images.githubusercontent.com/10504350/80610131-d27ec800-89ed-11ea-8311-df274a5cba52.png)

**Page 2 results (end):**
![image](https://user-images.githubusercontent.com/10504350/80610181-e296a780-89ed-11ea-9cdc-0aecef3001a3.png)

Expected:
- The displayed results to correspond to the current page.  For example; Page 1 results should not be displayed for any length of time when on Page 2.

**Comment by ianco** [comment]
Updated so that the search results will disappear and it will display "Performing search..." until the results are available to display

**Comment by WadeBarnes** [comment]
Resolved in 25c1c3a0b961ab4a0b82bd18b0ce0778a1d9bb18
