### ISSUE TITLE
Clicking the Previous button on the search results page takes you back to Page 1

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/aries-vcr#496]
Found in:
- 87c6bd423f537231d36ffa8ae8c26f91247f3b9f

Steps to reproduce:
- Perform a partial name search to return many results:
![image](https://user-images.githubusercontent.com/10504350/80609738-52f0f900-89ed-11ea-9dfa-3c57d540f69b.png)
- Make note of the page number in the URL and the list of results.
- Click **Next** a few times to go to, say, page 4.
- Make note of the page number in the URL and the list of results.
- Click **Previous**
- Make a note of the page number in the URL and the list of results.

Observed:
- You are taken all the way back to Page 1.
- The **Previous** button is disabled.

Expected:
- You are taken back to the previous page, and you still have the option of going the the previous of next page of results.

**Comment by ianco** [comment]
typescript code used min() function instead of max() :-(

**Comment by WadeBarnes** [comment]
Resolved in 25c1c3a0b961ab4a0b82bd18b0ce0778a1d9bb18
