### ISSUE TITLE
Real-time indexing does not seem to be functioning reliably  

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/aries-vcr#498]
Found in:
- 87c6bd423f537231d36ffa8ae8c26f91247f3b9f

Observed:
- Less then half of the credentials issued have been indexed.  See the results below.
- A some point during the data load the real-time indexing stopped functioning on one or more pods.  These pods (the api pods) are auto-scaled based on load.  There can be from 2 to 16 instances running at any given time.

Expected:
- Every credential received by the system to be indexed.

Example:
- From https://orgbook-test.pathfinder.gov.bc.ca/api/quickload during the data load performed over 2020-04-29 to 2020-04-30.
- `counts.actual_credential_count` is the actual number of credentials in the database, `credential_counts.total` is the number of credentials that have been indexed.  `indexes_synced` is `true` when `counts.actual_credential_count` == `credential_counts.total` meaning that all credentials in the system have been indexed.
- Records that have not been indexed will not appear in search results.

```
{
  "counts": {
    "claim": 30280350,
    "credential": 1613008,
    "credentialtype": 3,
    "issuer": 0,
    "topic": 1179886,
    "actual_credential_count": 1613096
  },
  "credential_counts": {
    "total": 444511,
    "active": 117430,
    "registrations": 29061,
    "last_month": 173427,
    "last_week": 173427,
    "last_24h": 23773
  },
  "demo": true,
  "indexes_synced": false
}
```

**Comment by WadeBarnes** [comment]
We have seen this in the past, but not for a while.  When this was occurring before there were places in  the real-time indexing code where an unhanded exception could cause the thread running the processing to crash and allow the API to continue to run without indexing any subsequent credentials.  The issue would persist until the pod was recycled; new pod, fresh start, and initialization.

**Comment by ianco** [comment]
@WadeBarnes do you recall if the previous issues we had were problems in our code?  Or some of the frameworks?

**Comment by WadeBarnes** [comment]
@ianco, Our code, the indexing components.

**Comment by WadeBarnes** [comment]
https://github.com/bcgov/aries-vcr/blob/master/server/vcr-server/vcr_server/utils/boot.py#L77

https://github.com/bcgov/aries-vcr/blob/master/server/vcr-server/vcr_server/utils/solrqueue.py#L12

https://github.com/bcgov/aries-vcr/blob/master/server/vcr-server/api/v2/search/index.py#L9

**Comment by ianco** [comment]
Thanks, investigating now ...

**Comment by WadeBarnes** [comment]
What was happening is an unhanded exception in either the `SolrQueue` or `TxnAwareSearchIndex` would cause the `SolrQueue` to crash.  The API would continue to run, but subsequent records would not be indexed.  Since the `SolrQueue` is only initialized on startup any affected containers would continue to operate in this mode until they were shutdown (manually or via auto-scaling).  Since there are a minimum of two instances of the API running, if those first two instances were affected the issue could persist for an indefinite period of time.  As new containers were spun up records received by these new instances would be indexed.

**Comment by ianco** [comment]
When I do a test load on my local this is what I get.  It looks like 1951 were indexed but there are only 875 in the database?

```
{
    "counts": {
        "actual_credential_count": 875,
        "claim": 14762,
        "credential": 875,
        "credentialtype": 3,
        "issuer": 1,
        "topic": 403
    },
    "credential_counts": {
        "active": 600,
        "last_24h": 875,
        "last_month": 875,
        "last_week": 875,
        "registrations": 288,
        "total": 1951
    },
    "demo": true,
    "indexes_synced": false
}
```

**Comment by ianco** [comment]
Adding a log relating to a recent error - loss of a solr database connection

**Comment by ianco** [comment]
[https://app.zenhub.com/files/162001451/155afdd2-36f1-42e2-b8e2-12bfc7c4a0e3/download](https://app.zenhub.com/files/162001451/155afdd2-36f1-42e2-b8e2-12bfc7c4a0e3/download)

**Comment by swcurran** [comment]
Closing this issue as I assume it is resolved. Please re-open (or add a new issue) if I'm mistaken.
