### ISSUE TITLE
Web-Dev not working

### ISSUE THREAD

**Issue by scottgorny** [bcgov/aries-vcr#503]
Tried to run AriesVCR in web-dev mode. 

Executed TRACE_TARGET=log ./manage web-dev seed=my_unique_seed_00000000000000000

Received the following error:

[start      ] Copying theme files to src/themes/_active
[start      ] Custom theme directory: themes
[start      ] Theme selected: base
[start      ] /opt/app-root/src/build-theme.js:129
[start      ]       throw err;
[start      ]       ^
[start      ] 
[start      ] Error: EACCES: permission denied, mkdir 'src/themes/_active'
[start      ]     at Object.fs.mkdirSync (fs.js:885:18)
[start      ]     at cleanTargetDir (/opt/app-root/src/build-theme.js:126:8)
[start      ]     at Object.<anonymous> (/opt/app-root/src/build-theme.js:352:3)
[start      ]     at Module._compile (module.js:653:30)
[start      ]     at Object.Module._extensions..js (module.js:664:10)
[start      ]     at Module.load (module.js:566:32)
[start      ]     at tryModuleLoad (module.js:506:12)
[start      ]     at Function.Module._load (module.js:498:3)
[start      ]     at Function.Module.runMain (module.js:694:10)
[start      ]     at startup (bootstrap_node.js:204:16)
npm info lifecycle vcr-web@2.0.0~dev: Failed to exec dev script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vcr-web@2.0.0 dev: `run-p --print-label --silent start watch-theme`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vcr-web@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 733ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app-root/src/.npm/_logs/2020-05-06T19_40_41_101Z-debug.log

I am running Linux Mint as my OS.

**Comment by WadeBarnes** [comment]
@scottgorny, Check the permissions on the folder of your working copy.  Folders from there are being mounted into the container.  It looks like the container does not have permissions to those folders.

Here are where the folders are being mounted; https://github.com/bcgov/aries-vcr/blob/master/docker/docker-compose.yml#L48

A quick way to verify whether this is the issue is to comment out that `volume` section in the yml file and try again.

**Comment by ianco** [comment]
Just FYI I tested this on my local and it was working fine

**Comment by WadeBarnes** [comment]
Works for me on Windows too.

**Comment by scottgorny** [comment]
Based on Stephen's comments, I had some success earlier today by chmod-ing the directory to give everyone/everything access. I noticed that the previous orgbook had all directories and files with a 777 access. I don't remember if I did that for some reason or not.

**Comment by WadeBarnes** [comment]
Thanks for the feedback.  Glad you got it working.
