### ISSUE TITLE
Make logging more configurable

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/aries-vcr#517]
Current logging (specifically with the API/Controller) is too verbose and it does not respect the available environment settings for logging.  There are section of the logging configuration that are hard coded to `DEBUG`; https://github.com/bcgov/aries-vcr/blob/master/server/vcr-server/vcr_server/settings.py#L203

This ends up causing GB worth of logs to be collected unnecessarily during data loads which has been causing issues for platform services, as they keep getting alerted to the high volume disk usage.

**Comment by WadeBarnes** [comment]
@ianco, would you mind looking at fixing this issue?

**Comment by esune** [comment]
I think this is a duplicate/close relative of #476 
@WadeBarnes can we close this issue and leave the other open instead?

**Comment by WadeBarnes** [comment]
It is, closing
