### ISSUE TITLE
Failed to ./manage start the docker image

### ISSUE THREAD

**Issue by Howlla** [bcgov/aries-vcr#520]
Trying to run the aries-vcr docker image using 
```./manage start seed=my_unique_seed_00000000000000000```

Gives the following output
Pulling echo-app (echo-app:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling echo-app (echo-app:)...
ERROR: pull access denied for echo-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by ianco** [comment]
If this happens there's probably a discrepancy between the docker images available and what `./manage start` is expecting.  For example you previously ran `./manage start`, then did a `./manage stop`, made some image changes, and then `./manage start` again.  For the most part, docker can deal with this, the problem can occur if the dependancies are replaced.

The best approach is to run `./manage rm`, this will remove any stopped containers, and then `./manage start`.  If the error persists, do a `./manage rm` and then rebuild the images again.

**Comment by swcurran** [comment]
It might also be you didn't do a `./manage build` before you did the `start`

**Comment by Howlla** [comment]
Yes removing volumes in my docker installation fixed the issue
