### ISSUE TITLE
aries_cloudagent.transport.outbound.manager ERROR

### ISSUE THREAD

**Issue by zbbgit** [bcgov/aries-vcr#558]
Down load the latest code, there is a ERROR when run the ./manage start , so what's the problem and  how to solve。

vcr-api_1      | Indexing 0 addresss
vcr-api_1      | Indexing 0 credentials
vcr-api_1      | Indexing 0 names
vcr-api_1      | Indexing 0 topics
vcr-agent_1    | 2020-09-01 09:20:03,344 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://vcr-api:8080/agentcb/topic/connections/; Error: (<class 'aiohttp.client_exceptions.ClientConnectorError'>, ClientConnectorError(ConnectionKey(host='vcr-api', port=8080, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(111, "Connect call failed ('172.29.0.9', 8080)")), <traceback object at 0x7f0ff6745748>); Re-queue failed message ...
vcr-api_1      | ======== Running on http://0.0.0.0:8080 ========
vcr-api_1      | (Press CTRL+C to quit)
vcr-api_1      | >>> YES updating cred type timestamp
vcr-api_1      | >>> YES create detail claims for credentials

**Comment by zbbgit** [comment]
in addtion，indy-node version is 1.12.3

**Comment by WadeBarnes** [comment]
That looks like a startup timing issue.  The API had not fully started when the call was made from the agent.  Startup timing can be adjusted in the https://github.com/bcgov/aries-vcr/blob/master/docker/docker-compose.yml.  You'll see a `sleep` in the startup command for each service.

The very first time you start `aries-vcr` there can be delays in the initialization of the various containers (database initialization, schema creation, etc).  Most of the time running a `./manage stop` followed by `./manage start` following such issues will result in things starting up in the expected order.

**Comment by zbbgit** [comment]
I have tried by running a ./manage stop followed by ./manage start，but still ERROR  exception .


vcr-api_1      | Indexing 0 topics
vcr-api_1      | ERROR 2020-09-02 01:17:43,534 base_events 7 140397517924096 Task exception was never retrieved
vcr-api_1      | future: <Task finished coro=<connect_agent() done, defined at /home/indy/vcr_server/utils/boot.py:73> exception=ConnectionError(MaxRetryError("HTTPConnectionPool(host='vcr-agent', port=8024): Max retries exceeded with url: /connections?alias=credential-registry-self (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb0c9f38588>: Failed to establish a new connection: [Errno 111] Connection refused',))",),)>
vcr-api_1      | Traceback (most recent call last):
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
vcr-api_1      |     (self._dns_host, self.port), self.timeout, **extra_kw
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
vcr-api_1      |     raise err
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
vcr-api_1      |     sock.connect(sa)
vcr-api_1      | ConnectionRefusedError: [Errno 111] Connection refused
vcr-api_1      |
vcr-api_1      | During handling of the above exception, another exception occurred:
vcr-api_1      |
vcr-api_1      | Traceback (most recent call last):
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
vcr-api_1      |     chunked=chunked,
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
vcr-api_1      |     conn.request(method, url, **httplib_request_kw)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/http/client.py", line 1239, in request
vcr-api_1      |     self._send_request(method, url, body, headers, encode_chunked)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/http/client.py", line 1285, in _send_request
vcr-api_1      |     self.endheaders(body, encode_chunked=encode_chunked)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/http/client.py", line 1234, in endheaders
vcr-api_1      |     self._send_output(message_body, encode_chunked=encode_chunked)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/http/client.py", line 1026, in _send_output
vcr-api_1      |     self.send(msg)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/http/client.py", line 964, in send
vcr-api_1      |     self.connect()
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/connection.py", line 187, in connect
vcr-api_1      |     conn = self._new_conn()
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
vcr-api_1      |     self, "Failed to establish a new connection: %s" % e
vcr-api_1      | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb0c9f38588>: Failed to establish a new connection: [Errno 111] Connection refused
vcr-api_1      |
vcr-api_1      | During handling of the above exception, another exception occurred:
vcr-api_1      |
vcr-api_1      | Traceback (most recent call last):
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
vcr-api_1      |     timeout=timeout
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
vcr-api_1      |     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
vcr-api_1      |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
vcr-api_1      | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='vcr-agent', port=8024): Max retries exceeded with url: /connections?alias=credential-registry-self (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb0c9f38588>: Failed to establish a new connection: [Errno 111] Connection refused',))
vcr-api_1      |
vcr-api_1      | During handling of the above exception, another exception occurred:
vcr-api_1      |
vcr-api_1      | Traceback (most recent call last):
vcr-api_1      |   File "/home/indy/vcr_server/utils/boot.py", line 82, in connect_agent
vcr-api_1      |     headers=settings.ADMIN_REQUEST_HEADERS,
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/requests/api.py", line 76, in get
vcr-api_1      |     return request('get', url, params=params, **kwargs)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/requests/api.py", line 61, in request
vcr-api_1      |     return session.request(method=method, url=url, **kwargs)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
vcr-api_1      |     resp = self.send(prep, **send_kwargs)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
vcr-api_1      |     r = adapter.send(request, **kwargs)
vcr-api_1      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
vcr-api_1      |     raise ConnectionError(e, request=request)
vcr-api_1      | requests.exceptions.ConnectionError: HTTPConnectionPool(host='vcr-agent', port=8024): Max retries exceeded with url: /connections?alias=credential-registry-self (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb0c9f38588>: Failed to establish a new connection: [Errno 111] Connection refused',))
vcr-api_1      | ======== Running on http://0.0.0.0:8080 ========
vcr-api_1      | (Press CTRL+C to quit)

**Comment by WadeBarnes** [comment]
Just pulled the latest code and ran `./manage build`, `./manage start` with a clean docker environment.  The application stated up without error.

A successful startup looks like this:
[aries-vcr-startup.log](https://github.com/bcgov/aries-vcr/files/5163773/aries-vcr-startup.log)

It looks like you are still having startup timing issues.  In your latest log the api (vcr-api_1) has started up before the agent (vcr-agent_1) and it can't establish a connection:
```
vcr-api_1 | requests.exceptions.ConnectionError: HTTPConnectionPool(host='vcr-agent', port=8024): Max retries exceeded with url: /connections?alias=credential-registry-self (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb0c9f38588>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

Without the whole log I can't tell when or if the agent is starting.  Compare my log with your's and try to identify where the startup timing is out of sync or if there is an error starting up one of the other services.  Then you can adjust the startup timing in the docker-compose file if needed.

**Comment by zbbgit** [comment]
There is also error " [Errno 111] Connection refused" in your log file.
Now，i have fallback version，no error occurred when run startup。
Thank you very much！

**Comment by WadeBarnes** [comment]
The `[Errno 111] Connection refused` errors in my log file are for `rabbitmq` (the connection from the workers to the `rabbitmq` server).  The workers will continue to attempt to connect to the server until the server is fully running and they are able to connect successfully.  You'll see this near the end of the log file.  This is normal.

The `[Errno 111] Connection refused` errors in your log snippet above is between the `api` and `agent` which causes issues.
