### ISSUE TITLE
Slow load of UI on Safari - 2 minutes (!!)

### ISSUE THREAD

**Issue by swcurran** [bcgov/aries-vcr#584]
Please investigate the slow loading of the BC OrgBook theme of Aries VCR on the most recent Safari.

See the vide from Peter: Heres a video showing the slow loading of orgbook I am getting using Safari vs Chrome. Something changed when Apple updated to Safari 14.0 https://youtu.be/On4ml88Aqzc

**Comment by ianco** [comment]
Looks like a delay loading "fathom.js"

**Comment by ianco** [comment]
![image](https://user-images.githubusercontent.com/1852309/96054380-662a4080-0e36-11eb-8b60-22214e1fb4ca.png)

**Comment by ianco** [comment]
... vs 13 msec on Chrome:

![Uploading image.png…]()

**Comment by ianco** [comment]
... referenced in the index page and nginx config, I'm assuming we can delete the reference?  There is no fathom.js ...

$ grep -in -r fathom ..
../docker/nginx-runtime/nginx.conf.template:117:        # serve the fathom analytics tracking code, if available
../docker/nginx-runtime/nginx.conf.template:118:        location =/fathom.js {
../client/themes/bcgov/index.html:9:  <script type="text/javascript" src="/fathom.js"></script>

**Comment by WadeBarnes** [comment]
@esune, ^

**Comment by esune** [comment]
The mapping for the configmap serving `fathom.js` was borked, fixed now - it should have resolved the issue.

Unsure why it would be a "slow load" situation on Safari and just a regular quick `404` on other browsers though, that is for Apple to discover 😅
