### ISSUE TITLE
Deploy an issuer controller/agent in OpenShift for BuyBC

### ISSUE THREAD

**Issue by ianco** [bcgov/aries-vcr#610]
Deploy an issuer in OpenShift (orgbook "dev" environment) for BuyBC developers to issue credentials to OrgBook

- deploy both the agent and issuer controller (based on the demo issuer) - create a new "buy-bc-issuer" github repo?
- requires security to be added to the controller "issue-credential" endpoint (e.g. api key)
- Buy BC will need to provide the configuration files (schema.yml and services.yml)

TODO should schedule a meeting with the buy bc folks to determine tasks and timeline

**Comment by swcurran** [comment]
@esune -- could you oversee this with @wadeking98 doing the heavy lifting?  This is the single instance version of the multi-tenant OrgBook issuer -- minus lots of features, of course (admin API, config API, etc.) -- so not a bad exercise in pursuing that goal.

**Comment by WadeBarnes** [comment]
@esune, I'd recommend provisioning this new issuer in the OCP4 environment.

**Comment by esune** [comment]
@WadeBarnes we do not have the appropriate namespace in OCP4 for this yet - the ToIP one...
