### ISSUE TITLE
Add tagging of releases of Aries VCR

### ISSUE THREAD

**Issue by swcurran** [bcgov/aries-vcr#618]
Please add a release tag for the components of Aries VCR that are currently in production for OrgBook BC so that we can easily see all changes since then. 

Please define a process for tagging all releases going forward that is set at least on every release to production.  Once we create a stronger separation between Aries VCR and OrgBook BC, we'll continue to designated tags on Aries VCR, independent of promotion to OrgBook BC.

**Comment by swcurran** [comment]
@WadeBarnes -- as soon as you have set the tag on what is currently in OrgBook BC production, please let me know so I can generate a release list of changes that will be promoted to production in the next release.

**Comment by WadeBarnes** [comment]
Revision in prod is `f7a05da5ba68db2ef650a3b22383d803d7ea9dab`.

**Comment by WadeBarnes** [comment]
@swcurran, https://github.com/bcgov/aries-vcr/releases/1.5.0

**Comment by WadeBarnes** [comment]
Process to follow.  This one was special since it's from an old commit.  I had to tag it locally and push it, then generate the release off the existing tag.
