### ISSUE TITLE
A hidden VC is showing up on the timeline when not needed

### ISSUE THREAD

**Issue by swcurran** [bcgov/aries-vcr#622]
I'm not sure what the algorithm is to determine if an extra credential is needed for a "hidden" credential -- e.g. one issued right before another one such that the first isn't visible on the timeline.

Example: https://orgbook.gov.bc.ca/en/organization/registration.registries.ca/BC1196841  in production with version 1.5.0.

Putting this in the backlog as the UX changes may eliminate the timeline. However, if we keep it, we should try to fix this (if reasonable to do).

**Comment by amanji** [comment]
Is this in reference to the Cannabis Retail Store License? I see two credentials in the set but it appears only one is on the timeline (likely they are overlapping because of the same 'effective_date').

**Comment by swcurran** [comment]
No.  The two credentials pointed to in Red are the same (not a duplicate, literally the same credential ID), the one pointed to in blue is the "Notice of Alteration".

The second, dark blue credential shouldn't be there at all, so must be another bug in the display.  :-(

![image](https://user-images.githubusercontent.com/1018050/106820099-a6087400-662f-11eb-86b7-319f092e8943.png)
