### ISSUE TITLE
Search results in OrgBook BC showing archived despite not selected

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/aries-vcr#641]
Some searches in the live OrgBook BC service are returning archived results, even when 'Archived' isn't selected in the search filters.

Example:
https://www.orgbook.gov.bc.ca/en/search/name?query=telus&inactive=false&page=1&issuer_id=&category:entity_type=

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/75134312/112070147-5d970e00-8b2a-11eb-963b-dfc50293b62a.png">

**Comment by amanji** [comment]
Related to https://github.com/bcgov/aries-vcr/pull/639. Requires reindexing of Topics since the last major index a few months ago.

Will sync up with @WadeBarnes to try and schedule this.
