### ISSUE TITLE
Please rename primary branch to main

### ISSUE THREAD

**Issue by swcurran** [bcgov/aries-vcr#688]
Not sure what automation needs to be changed in conjunction with this, so leaving it to be done by the SRE team.

Not urgent, but perhaps a wrap up task some afternoon.

**Comment by WadeBarnes** [comment]
I did a quick search.  There are a few DevOps projects, some ours, some others like Mines Digital Trust, that have static references to the default branch with it's current name.  Some of those references can easily be made dynamic by simply removing the branch reference, with others I'll need to have a closer look.  Once the references are dynamic (i.e. will automatically detect/use the default branch) renaming will be possible.

**Comment by WadeBarnes** [comment]
Done
