### ISSUE TITLE
Aries VCR ./manage "up" and then "down" leaves volumes

### ISSUE THREAD

**Issue by swcurran** [bcgov/aries-vcr#690]
I ran ./manage up and then ./manage down and noticed that a number of volumes remained.  Is there a way to clean those up?

The volumes were 2 unnamed ones and vcr_vcr-data, vcr_vcr-pip-cache, vcr_vcr-rabbit, vcr_vcr-wallet, and vcr_vcr-wallet-db

**Comment by WadeBarnes** [comment]
My results with the latest version of Aries VCR:
```
$ ./manage build
...
```
```
$ ./manage up
...
Creating network "vcr_vcr" with the default driver
Creating volume "vcr_vcr-data" with default driver
Creating volume "vcr_vcr-wallet" with default driver
Creating volume "vcr_vcr-wallet-db" with default driver
Creating volume "vcr_vcr-rabbit" with default driver
```
```
$ docker volume ls | grep vcr
local     vcr_vcr-data
local     vcr_vcr-pip-cache
local     vcr_vcr-rabbit
local     vcr_vcr-wallet
local     vcr_vcr-wallet-db
```
```
$ ./manage down
Stopping and removing any running containers ...
...
Removing network vcr_vcr
Removing volume vcr_vcr-data
Removing volume vcr_vcr-wallet
Removing volume vcr_vcr-wallet-db
Removing volume vcr_vcr-rabbit
Removing project volumes ...
vcr_vcr-pip-cache
Removing build cache ...
```
```
$ docker volume ls | grep vcr

```

The unnamed volumes will be anonymous volumes and may not be associated with Aries VCR.  The `vcr_vcr-pip-cache` volume comes from the `api` build.

**Comment by swcurran** [comment]
Weird.  I knew I should have tried it again.  Don't know why it didn't work the first time, when I was shutting down after running everything (UI, issuer) and putting data into the database.

Closing, and I'll keep watching.

**Comment by ianco** [comment]
I've had this issue if one of the dependent dockers doesn't shut down properly.  Usually there is an error message something like `ERROR: error while removing network: network vcr_vcr ...` and then docker doesn't finish with its cleanup
