### ISSUE TITLE
./manage build Command Fails

### ISSUE THREAD

**Issue by tko85** [bcgov/aries-vcr#731]
I am unable to build Aries VCR image on my local machine using Docker IAW the instructions in https://github.com/bcgov/aries-vcr/blob/main/docs/README.md .
Two issues:
1. After forking and cloning aries-vcr, there is no aries-vcr/starter-kits/credential-registry/docker folder.  The instructions state to cd into this folder before using the ./manage build command.  But this folder doesn’t exist after cloning.
2. If instead, I cd into the aries-vcr/docker folder and try the ./manage build command, I receive this error message:

Building solr-base image ...
unable to prepare context: unable to 'git clone' to temporary context directory: error initializing submodules: usage: git submodule [--quiet] add [-b <branch>] [-f|--force] [--name <name>] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] deinit [-f|--force] [--] <path>...
   or: git submodule [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--recursive] [--] [<path>...]
: exit status 1

Here are my git and OS versions:
git version 1.8.3.1
CentOS v7

**Comment by WadeBarnes** [comment]
Try upgrading git to start.  The version you are running is very old.

**Comment by tko85** [comment]
yum seems to think it's the latest version of git:

[root@itzvsi-6phqbstj itzuser]# yum install git
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * epel: mirror.dal.nexril.net
Package git-1.8.3.1-23.el7_8.x86_64 already installed and latest version
Nothing to do
[root@itzvsi-6phqbstj itzuser]# git version
git version 1.8.3.1

Any other suggestions?

**Comment by tko85** [comment]
I figured out how to get latest version of git by using this article.
https://computingforgeeks.com/install-git-2-on-centos-7/

Upgrading the version resolved the build error message.  
Thanks.
