### ISSUE TITLE
Unable to load docker config

### ISSUE THREAD

**Issue by mjour** [bcgov/aries-vcr#739]
I've forked the main branch of aries-vcr.
I got the error while building.
The error is same as:
![image](https://user-images.githubusercontent.com/96822355/220964041-70a9da44-16d3-40b5-9b4f-aab7e637411c.png)
How to fix it?

**Comment by WadeBarnes** [comment]
@mjour, I just pulled the latest code and did a `./manage build`, and it succeeded.

I'm using Docker Desktop on Windows 11
```
$ docker version
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:36:18 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.3 (96739)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by WadeBarnes** [comment]
Looks like your environment is having issues pulling `registry.access.redhat.com/ubi9/python-39:latest`.  Try running a `docker pull registry.access.redhat.com/ubi9/python-39:latest` to see if you can pull the image itself.

**Comment by mjour** [comment]
I've just download latest code and there is an different error.
![image](https://user-images.githubusercontent.com/96822355/220996021-bf436248-2fd7-4a20-b505-336f680795a4.png)

**Comment by ianco** [comment]
I'll look into that error

**Comment by ianco** [comment]
@mjour if you pull the latest this should be fixed

**Comment by mjour** [comment]
> @mjour if you pull the latest this should be fixed

I will retry it.

**Comment by mjour** [comment]
The latest codes does work well.
