### ISSUE TITLE
VCR main agent fails on start

### ISSUE THREAD

**Issue by kthomas-digicat** [bcgov/aries-vcr#749]
vcr-vcr-agent-1   | Traceback (most recent call last):
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 174, in open
vcr-vcr-agent-1   |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
vcr-vcr-agent-1   |     open_pool_ledger.cb)
vcr-vcr-agent-1   | indy.error.PoolLedgerTimeout
vcr-vcr-agent-1   | 
vcr-vcr-agent-1   | The above exception was the direct cause of the following exception:
vcr-vcr-agent-1   | 
vcr-vcr-agent-1   | Traceback (most recent call last):
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/provision.py", line 38, in provision
vcr-vcr-agent-1   |     if await ledger_config(root_profile, public_did and public_did.did, True):
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 71, in ledger_config
vcr-vcr-agent-1   |     async with ledger:
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 276, in __aenter__
vcr-vcr-agent-1   |     await self.pool.context_open()
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 209, in context_open
vcr-vcr-agent-1   |     await self.open()
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 174, in open
vcr-vcr-agent-1   |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/error.py", line 27, in __exit__
vcr-vcr-agent-1   |     ) from err_value
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 174, in open
vcr-vcr-agent-1   |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
vcr-vcr-agent-1   |     open_pool_ledger.cb)
vcr-vcr-agent-1   | aries_cloudagent.ledger.error.LedgerConfigError: Exception opening pool ledger default: Error: Pool timeout
vcr-vcr-agent-1   |   Caused by: Pool timeout
vcr-vcr-agent-1   | 
vcr-vcr-agent-1   | 
vcr-vcr-agent-1   | The above exception was the direct cause of the following exception:
vcr-vcr-agent-1   | 
vcr-vcr-agent-1   | Traceback (most recent call last):
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 193, in _run_module_as_main
vcr-vcr-agent-1   |     "__main__", mod_spec)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 85, in _run_code
vcr-vcr-agent-1   |     exec(code, run_globals)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/__main__.py", line 74, in <module>
vcr-vcr-agent-1   |     main(sys.argv)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/__main__.py", line 71, in main
vcr-vcr-agent-1   |     run(args)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/__main__.py", line 64, in run
vcr-vcr-agent-1   |     run_command(command, args)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/__init__.py", line 37, in run_command
vcr-vcr-agent-1   |     module.execute(argv)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/provision.py", line 62, in execute
vcr-vcr-agent-1   |     loop.run_until_complete(provision(settings))
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
vcr-vcr-agent-1   |     return future.result()
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/provision.py", line 45, in provision
vcr-vcr-agent-1   |     raise ProvisionError("Error during provisioning") from e
vcr-vcr-agent-1   | aries_cloudagent.commands.provision.ProvisionError: Error during provisioning
vcr-vcr-agent-1   | 
vcr-vcr-agent-1   | Shutting down
vcr-vcr-agent-1   | 2023-06-07 11:39:53,351 aries_cloudagent.commands.start ERROR Exception during startup:
vcr-vcr-agent-1   | Traceback (most recent call last):
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 174, in open
vcr-vcr-agent-1   |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
vcr-vcr-agent-1   |     open_pool_ledger.cb)
vcr-vcr-agent-1   | indy.error.PoolLedgerTimeout
vcr-vcr-agent-1   | 
vcr-vcr-agent-1   | The above exception was the direct cause of the following exception:
vcr-vcr-agent-1   | 
vcr-vcr-agent-1   | Traceback (most recent call last):
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 72, in init
vcr-vcr-agent-1   |     await startup
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 28, in start_app
vcr-vcr-agent-1   |     await conductor.setup()
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 101, in setup
vcr-vcr-agent-1   |     self.root_profile, self.setup_public_did and self.setup_public_did.did
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 71, in ledger_config
vcr-vcr-agent-1   |     async with ledger:
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 276, in __aenter__
vcr-vcr-agent-1   |     await self.pool.context_open()
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 209, in context_open
vcr-vcr-agent-1   |     await self.open()
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 174, in open
vcr-vcr-agent-1   |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/indy/sdk/error.py", line 27, in __exit__
vcr-vcr-agent-1   |     ) from err_value
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy.py", line 174, in open
vcr-vcr-agent-1   |     self.handle = await indy.pool.open_pool_ledger(self.name, pool_config)
vcr-vcr-agent-1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy/pool.py", line 88, in open_pool_ledger
vcr-vcr-agent-1   |     open_pool_ledger.cb)
vcr-vcr-agent-1   | aries_cloudagent.ledger.error.LedgerConfigError: Exception opening pool ledger default: Error: Pool timeout
vcr-vcr-agent-1   |   Caused by: Pool timeout
vcr-vcr-agent-1   | 
vcr-vcr-agent-1 exited with code 0

@WadeBarnes @ianco please can you help with this, I am unable to start the main vcr-agent, it seems to exit after starting.

**Comment by WadeBarnes** [comment]
It would help if you provided the steps you are performing that result in this error.  It looks like you might not have `von-network` running, or if you are pointing `aries-vcr` at another ledger, that that ledger is not accessible.

**Comment by kthomas-digicat** [comment]
> It would help if you provided the steps you are performing that result in this error. It looks like you might not have `von-network` running, or if you are pointing `aries-vcr` at another ledger, that that ledger is not accessible.

Thank you @WadeBarnes, I am running VON network locally on the same machine. I can access the frontend at port localhost:9000. Please can you point me to the docs where I can set the URL of VON on the VCR agent.

**Comment by kthomas-digicat** [comment]
Thanks a lot @WadeBarnes , it appears that I needed to set the <machine-ip> on the von-network as well. Your answer was spot on, it works as expected. Thanks again for your prompt help.
