### ISSUE TITLE
Determine options to switch search engine

### ISSUE THREAD

**Issue by esune** [bcgov/aries-vcr#761]
Our Solr implementation is performing poorly due to difficulty in optimizing the search indexes as well as not being well-suited to live in OpenShift. We should determine a viable option for a new search engine that we could switch the project to.

**Comment by WadeBarnes** [comment]
We should also mention Solr is not well supported by our current (Haystack based) toolset.  Supported backends are listed [here](https://django-haystack.readthedocs.io/en/latest/backend_support.html).

**Comment by WadeBarnes** [comment]
Since we've gotten the unbound queries somewhat under control (by blocking them), performance has been fantastic.

**Comment by swcurran** [comment]
From ZenHub issue:

See https://github.com/bcgov/orgbook-configurations/pull/137 for background information.

Possible options:
- OpenSearch: https://opensearch.org
- ElastcSearch: https://www.elastic.co/elasticsearch/

Acceptance Criteria:
- Determine best replacement option for the search engine
- Assess and plan required code changes inAries VCR to support the new service

**Comment by WadeBarnes** [comment]
Performance continues to be fantastic since we've blocked the unbound queries through expression filtering.

**Comment by swcurran** [comment]
So just close this issue and we can search for this if needed?

**Comment by WadeBarnes** [comment]
I think we still want to look at other options, since the support for Solr, at least with the tech stack we're using, is not great.  The fact that things are working makes that far less urgent though.

**Comment by swcurran** [comment]
I know that BC Registries is using Solr elsewhere, and it is really their project, their call.  Enterprise Apps is not going to be making such a change, or spending time on this.

**Comment by WadeBarnes** [comment]
So we leave it here and open for them.

**Comment by WadeBarnes** [comment]
I've taken it off our board.

**Comment by WadeBarnes** [comment]
Closing this issue, since we haven't had any issues since blocking unbounded search queries.

Related issue https://github.com/bcgov/aries-vcr/issues/762
