### ISSUE TITLE
OrgBook BC API returns a 400 Error

### ISSUE THREAD

**Issue by amanji** [bcgov/aries-vcr#765]
It was reported that the `(v3/v4)/search/topic` endpoint returns a 400 Error when paging past a certain number of results.

For example: https://orgbook.gov.bc.ca/api/v4/search/topic?ordering=-score&q=abc&inactive=false&latest=true&revoked=false

Returns 541 results

The first 10 pages of results can be accessed:

https://orgbook.gov.bc.ca/api/v4/search/topic?inactive=false&latest=true&ordering=-score&page=10&q=abc&revoked=false

The result of the 10th page shows a URL to the next page available:

![Image](https://github.com/bcgov/aries-vcr/assets/5605464/503e1bca-ee8b-431e-8bcc-c88d9b32c15d)

Accessing the 11th page onwards returns a 400 Error. This is consistent regardless of the query used.

![Image](https://github.com/bcgov/aries-vcr/assets/5605464/d873c3b2-5671-4d46-9161-ab23007ce661)

**Comment by swcurran** [comment]
That’s a “feature” that @WadeBarnes added to stop bots from scraping the database.

Who reported the issue?

**Comment by WadeBarnes** [comment]
@swcurran, Correct

**Comment by esune** [comment]
Closing as this is a known behaviour.

For context, the limit to query paging was introduced to avoid issues deriving from performing queries that fetch large data sets (unbounded) that would cause out-of-memory issues in the search engine.

References:
* https://github.com/bcgov/aries-vcr/issues/762
* https://github.com/bcgov/aries-vcr/issues/757
* https://github.com/bcgov/orgbook-configurations/pull/137#issuecomment-1723902252
