### ISSUE TITLE
Upgrade project to newer ACA-Py version

### ISSUE THREAD

**Issue by esune** [bcgov/aries-vcr#766]
`aries-vcr` (and related projects) is still using ACA-Py [0.7.1](https://github.com/bcgov/aries-vcr/blob/d322d070fb166243ebdec4c171b2bb2bdcfdfde5/docker/vcr-agent/Dockerfile#L1) and should be updated to use a more recent version of the agent.

This will require some regression testing work to ensure that breaking changes will not be affecting functionality, as well as updating the `issuer_registration` plugin to be compatible with the newer agent version (and handle gracefully breaking changes).

**Comment by WadeBarnes** [comment]
Refer to https://github.com/bcgov/DITP-DevOps/issues/18 for details and links regarding blocking issues that have been identified.

**Comment by WadeBarnes** [comment]
Specific blocking issue can be found starting here; https://github.com/bcgov/orgbook-configurations/issues/124#issuecomment-1887483015

Newer versions of ACA-Py don't work well with Aries-VCR.

**Comment by WadeBarnes** [comment]
Is this something we can look into while there is active development going on?  I'd like be able to upgrade OrgBook and BC Reg to [ghcr.io/hyperledger/aries-cloudagent-python:py3.9-indy-1.16.0-0.12.1](https://github.com/hyperledger/aries-cloudagent-python/pkgs/container/aries-cloudagent-python/210924301?tag=py3.9-indy-1.16.0-0.12.1)

**Comment by ianco** [comment]
Do we want to update OrgBook to support the V2 endpoints as part of this update?  (We need to leave V1 support in place obvs)

**Comment by WadeBarnes** [comment]
@esune?

**Comment by ianco** [comment]
FYI did a quick test - with an update to the aca-py version the BC Reg issuer is still able to register on startup (i.e. the issuer registration plug-in is working with an updated aca-py) but credential issuing is failing.  Not sure why looking into it ...

**Comment by WadeBarnes** [comment]
> FYI did a quick test - with an update to the aca-py version the BC Reg issuer is still able to register on startup (i.e. the issuer registration plug-in is working with an updated aca-py) but credential issuing is failing. Not sure why looking into it ...

Yes, that's the behavior I was seeing too.

**Comment by ianco** [comment]
> Yes, that's the behavior I was seeing too.

Something on the OrgBook side ...

**Comment by esune** [comment]
> Hah issue credential 2.0 was already implemented in OrgBook by @amanji

So the protocol is not the issue we're looking for? 🙂

**Comment by ianco** [comment]
Well theoretically both the V10 and V20 protocols should work.  The BC Reg issuer is issuing using V10 which is breaking with the newer aca-py version.  I'll figure that out and then also try testing the issuer using the V20 protocol.

**Comment by ianco** [comment]
I believe the cause is the "abbreviated webhooks" fix, where we don't send the entire payload with the webhook.  There's a `--debug-webhook` option on aca-py, I think we just need to enable this.  Just testing now but it should be a fairly simple fix  ...

**Comment by ianco** [comment]
See PR https://github.com/bcgov/aries-vcr/pull/783

I think this repo needs to be updated?  --> https://github.com/bcgov/orgbook-configurations

**Comment by WadeBarnes** [comment]
Thanks @ianco, I can update the other repo.  I'll likely use the `env` var form of the config to enable that.  Does that only need to be enabled on the OrgBook (holder) side?

**Comment by ianco** [comment]
> Does that only need to be enabled on the OrgBook (holder) side?

Yes, just on the OrgBook side.  The issuer is fine, no changes required.

PS for my local testing I used the updated aca-py for both issuer and OrgBook (they both use the same image built by the aries-vcr docker scripts).  Theoretically it should still work it we update OrgBook but leave the issuer on the older aca-py version, we may want to test that in our `test` environment ...

**Comment by WadeBarnes** [comment]
Deployment configuration changes here:
- https://github.com/bcgov/orgbook-configurations/pull/142
- https://github.com/bcgov/von-bc-registries-agent-configurations/pull/79
